<a href="https://colab.research.google.com/github/balogholiver07/Pytorch-Fun/blob/main/PytrochFun2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [3]:
np1 = np.random.rand(3, 4)
np1

array([[0.76893589, 0.28420547, 0.82747948, 0.23154654],
       [0.53397142, 0.39320273, 0.11273948, 0.92956268],
       [0.52652087, 0.51735352, 0.14210532, 0.59248027]])

In [4]:
np1.dtype

dtype('float64')

In [5]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 2.1612,  1.1235, -0.0520, -0.2242],
        [-1.0116, -1.0339, -0.0908, -2.4364],
        [-0.5237, -1.3272,  1.9196,  1.3395]])

In [6]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# Create tensor out of numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7689, 0.2842, 0.8275, 0.2315],
        [0.5340, 0.3932, 0.1127, 0.9296],
        [0.5265, 0.5174, 0.1421, 0.5925]], dtype=torch.float64)