<a href="https://colab.research.google.com/github/balogholiver07/Pytorch-Fun/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [4]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Reshape one dimensional array to two dimensional array
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch2 = torch.arange(15)

In [14]:
#Reshape if we dont know the number of items
my_torch2 = my_torch2.reshape(5, -1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [20]:
#Reshape with view
my_torch3 = torch.arange(15)
my_torch3 = my_torch3.view(5, 3)
my_torch3

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])